# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-11 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(upload_to='org/%Y/%m', verbose_name='\u5b66\u6821Logo'),
        ),
    ]
