# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-11 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180311_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='category',
            field=models.CharField(choices=[('100_school', '\u767e\u5f3a\u6821'), ('province_school', '\u7701\u91cd\u70b9'), ('fudao_org', '\u8f85\u5bfc\u673a\u6784')], default='province_school', max_length=25, verbose_name='\u7c7b\u522b'),
        ),
    ]
