# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-11 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_school_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='category',
            field=models.CharField(choices=[('bqx', '\u767e\u5f3a\u6821'), ('szd', '\u7701\u91cd\u70b9'), ('fdjg', '\u8f85\u5bfc\u673a\u6784')], default='province_school', max_length=25, verbose_name='\u7c7b\u522b'),
        ),
    ]
