# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-11 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20180311_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='course_nums',
            field=models.IntegerField(default=0, verbose_name='\u8bfe\u7a0b\u6570'),
        ),
        migrations.AddField(
            model_name='school',
            name='students',
            field=models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u4eba\u6570'),
        ),
        migrations.AlterField(
            model_name='school',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570'),
        ),
    ]
