# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-11 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20180311_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='students',
            new_name='student_nums',
        ),
    ]
