# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-12 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_course_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u8bfe\u65f6'),
        ),
    ]
