# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-04 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', '\u7537'), ('Female', '\u5973')], default='female', max_length=10),
        ),
    ]
